force-app/main/default/objects/Soft_Drink__c/Soft_Drink__c.object-meta.xml
<CustomObject>
    <label>Soft Drink</label>
    <nameField>
        <label>Drink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soft Drinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Soft_Drink_Order__c/Soft_Drink_Order__c.object-meta.xml
<CustomObject>
    <label>Soft Drink Order</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Soft Drink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soft Drink Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Soft Drink Orders</relationshipLabel>
    <relationshipName>Soft_Drink_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Soft_Drink__c.field-meta.xml
<CustomField>
    <fullName>Soft_Drink__c</fullName>
    <label>Soft Drink</label>
    <referenceTo>Soft_Drink__c</referenceTo>
    <relationshipLabel>Soft Drink Orders</relationshipLabel>
    <relationshipName>Soft_Drink_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountSummaryPrompt.cls
public class AccountSummaryPrompt {
    //CapabilityType='PromptTemplateType://einstein_gpt__fieldCompletion'
    @InvocableMethod(label='Soft Drink Orders'
                     description='Find Soft Drink for Account'
                     CapabilityType='PromptTemplateType://einstein_gpt__recordSummary')
    public static List<Response> getSoftDrinkData(List<Request> requests) {
        // Validate the expected number of requests as an input
        if (requests.size() != 1)
            throw new ListException('The requests list must contain one entry only');
        Account acc = requests[0].objectToSummarize;
        
        List<Soft_Drink_Order__c> SoftDrinkOrders =
            [SELECT Id,Soft_Drink__r.Name ,Quantity__c from Soft_Drink_Order__c 
             WHERE Account__c = :acc.Id ];
        string responseData = null;
        if(SoftDrinkOrders.isEmpty()) {
            responseData = 'There are no Soft Drink records.';
        } else {
            for(Soft_Drink_Order__c drink : SoftDrinkOrders) {  
                responseData =
                    (responseData != null) ? responseData + '\n' : '';           
                responseData += String.format('Soft Drink Details: {0}, {1}.',
                                              new List<Object>{drink.Soft_Drink__r.Name, drink.Quantity__c});
            }
        }
        
        List<Case> Cases =
            [SELECT Id , Reason , Subject ,Description from Case 
             WHERE AccountId = :acc.Id ];
        
        if(Cases.isEmpty()) {
            responseData += 'There are no Cases Records.';
        } else {
            for(Case ca : Cases) {  
                responseData =
                    (responseData != null) ? responseData + '\n' : '';           
                responseData += String.format('Case Details:- Subject , Reason , Description of the Case are as below: {0}, {1}, {2}.',
                                              new List<Object>{ca.Subject, ca.Reason , ca.Description});
            }
        }
        
        
        List<Response> responses = new List<Response>();
        Response res = new Response();
        res.Prompt = responseData;
        responses.add(res);
        return responses;
    }
    
    public class Request {
        @InvocableVariable(required=true)
        public Account objectToSummarize;
    }
    
    public class Response {
        @InvocableVariable
        public String Prompt;
    }
    
}