force-app/main/default/objects/Soft_Drink__c/Soft_Drink__c.object-meta.xml
<CustomObject>
    <label>Soft Drink</label>
    <nameField>
        <label>Drink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soft Drinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Soft_Drink__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Soft_Drink_Order__c/Soft_Drink_Order__c.object-meta.xml
<CustomObject>
    <label>Soft Drink Order</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Soft Drink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soft Drink Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Soft_Drink__c.field-meta.xml
<CustomField>
    <fullName>Soft_Drink__c</fullName>
    <label>Soft Drink</label>
    <referenceTo>Soft_Drink__c</referenceTo>
    <relationshipLabel>Soft Drink Orders</relationshipLabel>
    <relationshipName>Soft_Drink_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SoftDrinkOrderController.cls
public  with sharing class SoftDrinkOrderController {
    
   @InvocableMethod(label='Create Soft Drink Order' 
                     description='Create Soft Drink Order when User ask to create Soft Drink Order for example user Might say create a Soft Drink Order for the First Soft Drink Or create a Soft Drink Order for the Soft Drink Xyz')
    public static List<Soft_Drink_Order__c> createSoftDrinkOrder(List<Input> inputWrapper){

        Input inp = inputWrapper[0];

        //create  Soft_Drink_Order__c record fields are Soft_Drink__c, Quantity__c, Price__c
        Soft_Drink_Order__c sdo = new Soft_Drink_Order__c();
        sdo.Soft_Drink__c = inp.softDrinkID;
        sdo.Quantity__c = inp.Quantity;
        sdo.Price__c = inp.price;
        insert sdo;

        return new List<Soft_Drink_Order__c>{sdo};


    }

    public class Input {
        @InvocableVariable(required=true)
        public String softDrinkID;
        @InvocableVariable(required=true)
        public Integer Quantity;
        @InvocableVariable(required=true)
        public Double price;
    }

}