force-app/main/default/objects/Soft_Drink_Order__c/Soft_Drink_Order__c.object-meta.xml
<CustomObject>
    <label>Soft Drink Order</label>
    <nameField>
        <displayFormat>SD-{00000000}</displayFormat>
        <label>Soft Drink Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Soft Drink Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Soft_Drink_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SoftDrinkOrderStatus.cls
public without sharing class SoftDrinkOrderStatus {
    
 @InvocableMethod(label='Order Status' 
                 description='Return Status of the Soft Drink Order , when user ask for it, for example user can say what is the status of My Soft Drink order ABC')
    public static List<String> getStatus(List<Integer> orderNumber){
        
        Soft_Drink_Order__c sd = [Select ID,Status__c from Soft_Drink_Order__c where Order_Number__c=:orderNumber[0] ];
        return new List<String> { sd.Status__c };

    }
}